[package]
name = "pinocchio_err"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
proc_macro = true

[dependencies]
pinocchio.workspace = true
quote.workspace = true
syn.workspace = true
