[package]
name = "pinocchio-system"
description = "Pinocchio helpers to invoke System program instructions"
version = "0.0.0"
edition = "2021"

[dependencies]
pinocchio = { version="^0", path="../../sdk" }
